/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IntentSwapInterface extends Interface {
    getFunction(nameOrSignature: "executeSwap" | "owner" | "simulateSwap" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SwapExecuted" | "SwapSimulated"): EventFragment;

    encodeFunctionData(functionFragment: 'executeSwap', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'simulateSwap', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'executeSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'simulateSwap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace SwapExecutedEvent {
      export type InputTuple = [user: AddressLike, fromToken: string, toToken: string, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, fromToken: string, toToken: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {user: string, fromToken: string, toToken: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapSimulatedEvent {
      export type InputTuple = [user: AddressLike, fromToken: string, toToken: string, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, fromToken: string, toToken: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {user: string, fromToken: string, toToken: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IntentSwap extends BaseContract {
    
    connect(runner?: ContractRunner | null): IntentSwap;
    waitForDeployment(): Promise<this>;

    interface: IntentSwapInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    executeSwap: TypedContractMethod<
      [fromToken: string, toToken: string, amount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    simulateSwap: TypedContractMethod<
      [fromToken: string, toToken: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'executeSwap'): TypedContractMethod<
      [fromToken: string, toToken: string, amount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'simulateSwap'): TypedContractMethod<
      [fromToken: string, toToken: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'SwapExecuted'): TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
getEvent(key: 'SwapSimulated'): TypedContractEvent<SwapSimulatedEvent.InputTuple, SwapSimulatedEvent.OutputTuple, SwapSimulatedEvent.OutputObject>;

    filters: {
      
      'SwapExecuted(address,string,string,uint256,uint256)': TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
      SwapExecuted: TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
    

      'SwapSimulated(address,string,string,uint256,uint256)': TypedContractEvent<SwapSimulatedEvent.InputTuple, SwapSimulatedEvent.OutputTuple, SwapSimulatedEvent.OutputObject>;
      SwapSimulated: TypedContractEvent<SwapSimulatedEvent.InputTuple, SwapSimulatedEvent.OutputTuple, SwapSimulatedEvent.OutputObject>;
    
    };
  }